[project]
name = "spotify-aws-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vishalmuralikumar", email = "vishalmuralikumar959@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.98",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
spotify-aws-data-pipeline = "spotify_aws_data_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
